spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGERS_DB_NAME:notification}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:123}
    driverClassName: org.postgresql.Driver
    sql-script-encoding: UTF-8
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: GMT+4
    hibernate:
      ddl-auto: update

server:
  port: 8081

crawler.service.host: http://localhost
crawler.service.port: 8080
crawler.service.item-path: /api/v1/items
crawler.service.run-path: /api/v1/runs

userdata.service.host: http://localhost
userdata.service.port: 8080
userdata.service.path: /api/v1/users

userdatadictionary.service.host: http://localhost
userdatadictionary.service.port: 8080
userdatadictionary.service.items-to-find-path: /api/v1/ItemsToFind
userdatadictionary.service.price-settings-path: /api/v1/PriceSetting

sender.servie.host: http://localhost
sender.servie.port: 8080
sender.servie.path: /api/v1/sender

#---
#spring:
#  profiles: test
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration, org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration, org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

